FROM --platform=linux/amd64 ubuntu:20.04 as builder
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential libreadline-dev autoconf-archive libgmp-dev expect flex bison automake m4 libtool pkg-config libffi-dev

COPY . /bic
WORKDIR /bic
RUN autoreconf -i
RUN ./configure --enable-debug
RUN make -j8

FROM ubuntu:20.04 as package
COPY --from=builder /bic/src/genaccess /
